bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
make: Entering directory '/workdir/etc'
Running setup_env_vars.sh...
In etc/setup/setup_env_vars.sh
[34m[1/4][0m Detected OS type: linux-gnu
[34m[2/4][0m Setting PYTHONPATH=:/workdir/src
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[34m[3/4][0m Python-dotenv already installed
[34m[4/4][0m Exporting /workdir/.env
Loading environment variables...
DEBUG: Environment variables:
MODEL=/workdir/models
ETC=/workdir/etc
PYTHONPATH=:/workdir/src
WORKINGDIR=/workdir
EXAMPLES=/workdir/examples
TESTS=/workdir/tests
CONFIG=/workdir/etc/config
Running setup_config_files.sh...
In etc/setup/setup_config_file.sh
[34m[1/5][0m Detected OS type: linux-gnu
[34m[2/5][0m Sourcing environment variables
[34m[3/5][0m Creating benchmark download dir at /workdir/etc/config/mimic3-benchmark
[34m[4/5][0m Downloading itemid_to_variable_map.csv
--2024-10-11 11:54:14--  https://raw.githubusercontent.com/YerevaNN/mimic3-benchmarks/master/mimic3benchmark/resources/itemid_to_variable_map.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 991328 (968K) [text/plain]
Saving to: â€˜/workdir/etc/config/mimic3-benchmark/itemid_to_variable_map.csvâ€™

     0K .......... .......... .......... .......... ..........  5% 1.93M 0s
    50K .......... .......... .......... .......... .......... 10% 2.36M 0s
   100K .......... .......... .......... .......... .......... 15% 5.26M 0s
   150K .......... .......... .......... .......... .......... 20% 3.06M 0s
   200K .......... .......... .......... .......... .......... 25% 3.23M 0s
   250K .......... .......... .......... .......... .......... 30% 2.37M 0s
   300K .......... .......... .......... .......... .......... 36% 7.37M 0s
   350K .......... .......... .......... .......... .......... 41% 3.09M 0s
   400K .......... .......... .......... .......... .......... 46% 6.20M 0s
   450K .......... .......... .......... .......... .......... 51% 2.83M 0s
   500K .......... .......... .......... .......... .......... 56% 6.99M 0s
   550K .......... .......... .......... .......... .......... 61% 2.27M 0s
   600K .......... .......... .......... .......... .......... 67% 6.21M 0s
   650K .......... .......... .......... .......... .......... 72% 2.35M 0s
   700K .......... .......... .......... .......... .......... 77% 5.18M 0s
   750K .......... .......... .......... .......... .......... 82% 3.63M 0s
   800K .......... .......... .......... .......... .......... 87% 10.8M 0s
   850K .......... .......... .......... .......... .......... 92% 5.38M 0s
   900K .......... .......... .......... .......... .......... 98% 3.65M 0s
   950K .......... ........                                   100%  105M=0.3s

2024-10-11 11:54:14 (3.61 MB/s) - â€˜/workdir/etc/config/mimic3-benchmark/itemid_to_variable_map.csvâ€™ saved [991328/991328]

[34m[5/5][0m Downloading hcup_ccs_2015_definitions.yaml
--2024-10-11 11:54:14--  https://raw.githubusercontent.com/YerevaNN/mimic3-benchmarks/master/mimic3benchmark/resources/hcup_ccs_2015_definitions.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 159388 (156K) [text/plain]
Saving to: â€˜/workdir/etc/config/mimic3-benchmark/hcup_ccs_2015_definitions.yamlâ€™

     0K .......... .......... .......... .......... .......... 32% 1.95M 0s
    50K .......... .......... .......... .......... .......... 64% 3.40M 0s
   100K .......... .......... .......... .......... .......... 96% 2.93M 0s
   150K .....                                                 100%  136M=0.06s

2024-10-11 11:54:14 (2.71 MB/s) - â€˜/workdir/etc/config/mimic3-benchmark/hcup_ccs_2015_definitions.yamlâ€™ saved [159388/159388]

Skipping setup_conda_env step because IS_DOCKER is set to 1.
Skipping setup_tests step because testing is not enabled. Set testing=true to setup tests.
make: Leaving directory '/workdir/etc'
In etc/config-env.sh
[34m[1/2][0m Detected OS type: linux-gnu
[34m[2/2][0m Sourcing .env file at /workdir/.env
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/_pytest/main.py", line 279, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1118, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pluggy/_hooks.py", line 535, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls.copy(), kwargs, False)
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/workdir/tests/conftest.py", line 32, in pytest_configure
INTERNALERROR>     datasets.load_data(chunksize=75835,
INTERNALERROR>   File "/workdir/src/datasets/__init__.py", line 180, in load_data
INTERNALERROR>     reader = extraction.iterative_extraction(storage_path=extracted_storage_path,
INTERNALERROR>   File "/workdir/src/datasets/extraction/__init__.py", line 330, in iterative_extraction
INTERNALERROR>     patients_df = read_patients_csv(source_path)
INTERNALERROR>   File "/workdir/src/datasets/extraction/__init__.py", line 453, in read_patients_csv
INTERNALERROR>     patients_df = pd.read_csv(Path(dataset_folder, "PATIENTS.csv"),
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
INTERNALERROR>     return _read(filepath_or_buffer, kwds)
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
INTERNALERROR>     parser = TextFileReader(filepath_or_buffer, **kwds)
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
INTERNALERROR>     self._engine = self._make_engine(f, self.engine)
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
INTERNALERROR>     self.handles = get_handle(
INTERNALERROR>   File "/opt/conda/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
INTERNALERROR>     handle = open(
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/workdir/tests/data/mimiciii-demo/PATIENTS.csv'
[32mTEST[0m --- [97m10-11 11:54:16[0m : conftest.py ------------------------------------------- : [96mL 31  [0m [32m-[0m Loading preproceesing data for task IHM...